package balls.model;

public enum EventType {
    MOVE_BALL,
    NORTH_LIMIT_REACHED,
    SOUTH_LIMIT_REACHED,
    EAST_LIMIT_REACHED,
    WEST_LIMIT_REACHED,
    BALL_ENTERS_OCCUPIED_ROOM,
    BALL_ENTERS_FREE_ROOM,
    BALL_MOVES_INSIDE_ROOM,
    BALL_EXITS_ROOM
}
