package asteroid.model;

public enum EventType {
    MOVE_ASTEROID,
    NORTH_LIMIT_REACHED,
    SOUTH_LIMIT_REACHED,
    EAST_LIMIT_REACHED,
    WEST_LIMIT_REACHED,
    ASTEROID_ENTERS_OCCUPIED_ROOM,
    ASTEROID_ENTERS_FREE_ROOM,
    ASTEROID_MOVES_INSIDE_ROOM,
    ASTEROID_EXITS_ROOM
}
